- name: Deploy Docker Compose with Environment Variables
  hosts: localhost
  tasks:
      - name: Login in docker hub with user
        community.general.docker_login:
            username: "tathagat10" #add your docker id 
            password: "lmandnjr10"  #add your docker pw
      - name: git pull
        ansible.builtin.shell: git pull https://github.com/tathagat11/Task-Manager-MERN.git
      - name: Stop Docker containers
        ansible.builtin.shell: docker stop clientcontainer
        ignore_errors: true
      - name: Delete Docker container
        ansible.builtin.shell: docker rm clientcontainer
        ignore_errors: true
      - name: Delete Docker image
        ansible.builtin.shell: docker rmi tathagat10/client:latest
        ignore_errors: true
      - name: Build Docker image
        ansible.builtin.shell: docker build -t tathagat10/client:latest /var/lib/jenkins/workspace/Task-Manager/client/
        # ansible.builtin.shell: docker build -t tathagat10/client:latest /home/tathagat/Desktop/sem2/SPE/Task-Manager-MERN/client/
      - name: Push Docker image to Docker Hub
        community.general.docker_image:
            name: tathagat10/client
            tag: latest
            push: yes
            source: local
      - name: Pull Docker image from Docker Hub
        ansible.builtin.shell: docker pull tathagat10/client:latest
      - name: docker run
        ansible.builtin.shell: docker run -p 3000:80 --name clientcontainer -it -d tathagat10/client:latest 