- name: Kubernetes
  hosts: localhost
  
  tasks:
    
      - name: Login in docker hub with user
        community.general.docker_login:
            username: "tathagat10"
            password: "lmandnjr10"
      # - name: Start Minikube
      #   ansible.builtin.shell: minikube start
      # - name: Delete pods if running2
      #   ansible.builtin.shell: kubectl delete -f /home/tathagat/Desktop/sem2/SPE/Task-Manager-MERN/server/kubernetes.yml
      #   ignore_errors: true
      # - name: Sleep
      #   ansible.builtin.shell: sleep 30
      - name: Stop Docker containers
        community.general.docker_container:
            name: servercontainer
            state: absent
      - name: Delete Docker image
        community.general.docker_image:
            name: tathagat10/server
            tag: latest
            state: absent
        ignore_errors: true
      - name: Build Docker image
        community.general.docker_image:
            name: tathagat10/server
            tag: latest
            source: build
            build:
                path: /var/lib/jenkins/workspace/Task-Manager/server/
                dockerfile: Dockerfile
      - name: Push Docker image to Docker Hub
        community.general.docker_image:
            name: tathagat10/server
            tag: latest
            push: yes
            source: local
      - name: Pull Docker image from Docker Hub
        community.general.docker_image:
            name: tathagat10/server
            tag: latest
            source: pull
            force_source: yes
      - name: docker run
        ansible.builtin.shell: docker run -p 4001:4000 -h servercontainer -it -d tathagat10/server:latest 
        # community.general.docker_container:
        #     name: servercontainer
        #     image: tathagat10/server:latest
        #     ports:
        #         - 2368:4000
        #     command:
      # - name: Install Helm (using curl)
      #   become: yes
      #   shell: |
      #     curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      #     chmod 700 get_helm.sh
      #     ./get_helm.sh
      # - name: Add repo ngrok
      #   ansible.builtin.shell: helm repo add ngrok https://ngrok.github.io/kubernetes-ingress-controller
      # - name: Install ngrok Ingress Controller & Creating namespace
      #   ansible.builtin.shell: helm upgrade -i ngrok-ingress-controller ngrok/kubernetes-ingress-controller --namespace ngrok-ingress-controller --create-namespace --set credentials.apiKey="2g9mbKZ2U0rApq40XmTMQX3bFFN_5CnoMJSUmLXFPCyC9CiBn" --set credentials.authtoken="2Y1j9GAfrNrhU1K3lsaN9z6t3bq_2S3kAx1xRDNKpfYvSMTqL"
      #   ignore_errors: true
      # - name: Create pods
      #   ansible.builtin.shell: kubectl create -f /home/tathagat/Desktop/sem2/SPE/Task-Manager-MERN/server/kubernetes.yml


# export NGROK_API_KEY=2g9mbKZ2U0rApq40XmTMQX3bFFN_5CnoMJSUmLXFPCyC9CiBn
# export NGROK_AUTHTOKEN=2Y1j9GAfrNrhU1K3lsaN9z6t3bq_2S3kAx1xRDNKpfYvSMTqL

# helm install ngrok-ingress-controller ngrok/kubernetes-ingress-controller --set credentials.apiKey=$NGROK_API_KEY --set credentials.authtoken=$NGROK_AUTHTOKEN