- name: Kubernetes
  hosts: localhost
  tasks:
      - name: Login in docker hub with user
        community.general.docker_login:
            username: "tathagat10"
            password: "lmandnjr10"
      - name: Stop Docker containers
        ansible.builtin.shell: docker stop servercontainer
        ignore_errors: true
      - name: Delete Docker container
        ansible.builtin.shell: docker rm servercontainer
        ignore_errors: true
      - name: Delete Docker image
        ansible.builtin.shell: docker rmi tathagat10/server:latest
        ignore_errors: true
      - name: Build Docker image
        ansible.builtin.shell: docker build -t tathagat10/server:latest /var/lib/jenkins/workspace/Task-Manager/server/
        # ansible.builtin.shell: docker build -t tathagat10/server:latest /home/tathagat/Desktop/sem2/SPE/Task-Manager-MERN/server/
      - name: Push Docker image to Docker Hub
        community.general.docker_image:
            name: tathagat10/server
            tag: latest
            push: yes
            source: local
      - name: Pull Docker image from Docker Hub
        ansible.builtin.shell: docker pull tathagat10/server:latest
      - name: docker run
        ansible.builtin.shell: docker run -p 4001:4000 --name servercontainer -it -d tathagat10/server:latest 
       