apiVersion: v1
kind: Service
metadata:
    name: server
spec:
    ports:
        - name: http
          port: 4000
          targetPort: 4000
    selector:
        app: server
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: server
spec:
    replicas: 2
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: tathagat10/server
                  ports:
                      - name: http
                        containerPort: 4000
---