apiVersion: v1
kind: Service
metadata:
    name: server
    namespace: ngrok-ingress-controller
spec:
    ports:
        - name: http
          port: 4000
          targetPort: 4000
    selector:
        app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: server
    namespace: ngrok-ingress-controller
spec:
    replicas: 2
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: tathagat10/server
                  ports:
                      - name: http
                        containerPort: 4000
---
# ngrok Ingress Controller Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: server-ingress
    namespace: ngrok-ingress-controller
    annotaions:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:5173"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
    ingressClassName: ngrok
    rules:
        - host: magpie-more-monkfish.ngrok-free.app
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: server
                            port:
                                number: 4000